### ISSUE TITLE
How can I get the 27 features map as your paper said.

### ISSUE THREAD

**Issue by lishengjie5211** [egundogdu/CFCF#2]
There are 3 feature maps in the zeroth layer, 96 feature maps in the first layer and 32 feature maps in the last layer. They add up to 131 feature maps which is not 27 feature maps. 
Thanks in advance.

**Comment by egundogdu** [comment]
Thank you for you interest. The tracker configuration that makes use of 27 feature maps employ our custom network which outputs 8 feature maps as shown in Figure 2. For 27 feature maps, 3 RGB channels, 16 first layer feature maps and the final layer with 8 feature maps are used. The numbers you mentioned belong to VGG-M+our 32 feature maps.

**Comment by lishengjie5211** [comment]
Get it. I think I should read your paper more seriously.
Thanks for your reply!

**Comment by iou1992** [comment]
Hi,
i replace VGG model used in C-COT with CFCFNet.mat. Moreover, i replace Conjugate Gradient Descent Iteration number with 1.and then run the demo.m in the C-COT code.but there are 3 feature maps in the zeroth layer, 96 feature maps in the first layer and 512 feature maps in the last layer. why?
Thanks.

**Comment by egundogdu** [comment]
Hi,
If you make these changes to C-COT, it is normal that you have these number of feature maps since zeroth layer feature maps are nothing but RGB, and the rest is consistent with VGG model used. I could not understand your question clearly.

**Comment by egundogdu** [comment]
If you mean the 27 feature maps as in the title of the issue, it was an internal network that we used for ablation study of feature types. Hence, it is no longer available.

**Comment by iou1992** [comment]
Yes.I mean the 27 feature  maps as in the title of the issue.
There are 27 feature maps in MCFCF_CCOT. and  MCFCF_CCOT is a simple test compared to 611 feature maps of CCOT.  the above is my understanding. Is it right?
Thanks for your reply!
